# Generated by Django 6.0.2 on 2026-03-03 03:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_populate_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(upload_to=api.models.book_cover_upload_path),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.book_file_upload_path
            ),
        ),
    ]
