# Generated by Django 6.0.3 on 2026-03-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_adminactivity_bookapprovalstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
