# Generated by Django 6.0.3 on 2026-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='attribution_name',
            field=models.CharField(blank=True, help_text='Name or organization to attribute the book to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='attribution_url',
            field=models.URLField(blank=True, help_text='Link to the original source', max_length=500, null=True),
        ),
    ]
