from django.urls import path
from . import views

urlpatterns = [
    path('categories/', views.categories, name='categories'),
    path('books/', views.books, name='books'),
    path('books/<int:pk>/', views.book_detail, name='book-detail'),
    path('books/<int:pk>/view/', views.book_view, name='book-view'),
    path('books/<int:pk>/download/', views.book_download, name='book-download'),
    path('books/<int:pk>/reviews/', views.book_reviews, name='book-reviews'),
    path('books/<int:pk>/progress/', views.reading_progress, name='reading-progress'),
    path('shelves/', views.user_shelves, name='user-shelves'),
    path('shelves/<int:pk>/', views.remove_from_shelf, name='remove-from-shelf'),
    path('quote/today/', views.today_quote, name='today-quote'),
    path('my-books/', views.user_uploaded_books, name='user-uploaded-books'),
    path('new-arrivals/', views.new_arrivals, name='new-arrivals'),
    path('recent-books/', views.recent_books, name='recent-books'),
    path('recent-readings/', views.recent_readings, name='recent-readings'),
    path('user-reviews-count/', views.user_reviews_count, name='user-reviews-count'),
    path('admin/stats/', views.admin_dashboard_stats, name='admin-stats'),
    path('admin/activities/', views.admin_recent_activities, name='admin-activities'),
    path('admin/pending-books/', views.admin_pending_books, name='admin-pending-books'),
    path('admin/books/', views.admin_all_books, name='admin-all-books'),
    path('admin/users/', views.admin_all_users, name='admin-all-users'),
    path('admin/users/<int:user_id>/', views.admin_user_detail, name='admin-user-detail'),
    path('admin/books/<int:book_id>/approve/', views.approve_book, name='approve-book'),
    path('admin/books/<int:book_id>/reject/', views.reject_book, name='reject-book'),
    path('admin/books/<int:book_id>/delete/', views.admin_delete_book, name='admin-delete-book'),
    path('admin/books/<int:book_id>/toggle-visibility/', views.admin_toggle_book_visibility, name='admin-toggle-book-visibility'),
]
