# Generated by Django 6.0.2 on 2026-03-03 03:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recent_books",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.avatar_upload_path
            ),
        ),
    ]
